version: '3.8'

x-db-variables: &db-variables
 MYSQL_DATABASE: rzinv
 MYSQL_ROOT_PASSWORD: root
 MYSQL_USER: admin
 MYSQL_PASSWORD: R3dZ0mb13!
 MYSQL_PORT: 3306
 
services:

  RZINV:
    build: .
    image: rzinventory
    restart: on-failure
    depends_on:
     - mysql
    ports:
     - 8080:8080
    environment:
      SPRING_DATASOURCE_DATABASE: rzinv
      SPRING_DATASOURCE_ROOT_PASSWORD: root
      SPRING_DATASOURCE_USER: admin
      SPRING_DATASOURCE_PASSWORD: R3dZ0mb13!
      SPRING_DATASOURCE_PORT: 3306
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/rzinv?useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true

  mysql:
    image: "${DOCKER_MYSQL_IMAGE:-mysql:8.0}"
    ports:
     - 3306:3306
    environment:
     <<: *db-variables

volumes:
  rzinv-db:
