spring:
 application:
  name: RZINV
 thymeleaf:
  cache: false
  enabled: true
 logging:
  level:
    org:
      springframework: TRACE
 datasource:
  url: jdbc:mysql://34.133.158.65:3306/rzinv?useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true
  driver-class-name: com.mysql.cj.jdbc.Driver 
  platform: mysql
  username: RedZombieAdmin
  password: R3dZ0mb13!
  flyway:
   baseline-on-migrate: true
   schemas: ['rzinv']
   user: RedZombieAdmin
   password: R3dZ0mb13!
   url: jdbc:mysql://34.133.158.65:3306/rzinv?useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true
 server:
  servlet:
   session:
    tracking-modes: cookie
  port: 8080
logging:
  level:
    org:
      springframework: 
        security: DEBUG